/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'IconTabler:copy': typeof import('~icons/tabler/copy')['default']
    'IconTabler:list': typeof import('~icons/tabler/list')['default']
    'IconTabler:markdown': typeof import('~icons/tabler/markdown')['default']
    'IconTabler:minus': typeof import('~icons/tabler/minus')['default']
    'IconTabler:moon': typeof import('~icons/tabler/moon')['default']
    'IconTabler:plus': typeof import('~icons/tabler/plus')['default']
    'IconTabler:spellcheck': typeof import('~icons/tabler/spellcheck')['default']
    'IconTabler:sun': typeof import('~icons/tabler/sun')['default']
    'IconTabler:textSpellcheck': typeof import('~icons/tabler/text-spellcheck')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
